
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'DIVIDE ID LPAREN MINUS NUMBER PLUS RPAREN TIMESexpression : expression PLUS expressionexpression : expression MINUS expressionexpression : expression TIMES expressionexpression : expression DIVIDE expressionexpression : LPAREN expression RPARENexpression : NUMBERexpression : ID'
    
_lr_action_items = {'LPAREN':([0,2,5,6,7,8,],[2,2,2,2,2,2,]),'NUMBER':([0,2,5,6,7,8,],[3,3,3,3,3,3,]),'ID':([0,2,5,6,7,8,],[4,4,4,4,4,4,]),'$end':([1,3,4,10,11,12,13,14,],[0,-6,-7,-1,-2,-3,-4,-5,]),'PLUS':([1,3,4,9,10,11,12,13,14,],[5,-6,-7,5,5,5,5,5,-5,]),'MINUS':([1,3,4,9,10,11,12,13,14,],[6,-6,-7,6,6,6,6,6,-5,]),'TIMES':([1,3,4,9,10,11,12,13,14,],[7,-6,-7,7,7,7,7,7,-5,]),'DIVIDE':([1,3,4,9,10,11,12,13,14,],[8,-6,-7,8,8,8,8,8,-5,]),'RPAREN':([3,4,9,10,11,12,13,14,],[-6,-7,14,-1,-2,-3,-4,-5,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expression':([0,2,5,6,7,8,],[1,9,10,11,12,13,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expression","S'",1,None,None,None),
  ('expression -> expression PLUS expression','expression',3,'p_expression_plus','dataloader.py',42),
  ('expression -> expression MINUS expression','expression',3,'p_expression_minus','dataloader.py',46),
  ('expression -> expression TIMES expression','expression',3,'p_expression_times','dataloader.py',50),
  ('expression -> expression DIVIDE expression','expression',3,'p_expression_divide','dataloader.py',54),
  ('expression -> LPAREN expression RPAREN','expression',3,'p_expression_group','dataloader.py',58),
  ('expression -> NUMBER','expression',1,'p_expression_number','dataloader.py',62),
  ('expression -> ID','expression',1,'p_expression_id','dataloader.py',66),
]
